<?php

/**
 * @file
 * A light-weight, customizable lightbox plugin for jQuery 1.3
 */

/**
 * The default path to the Colorbox directory.
 */
define('COLORBOX_MIN_PLUGIN_VERSION', '1.5.14');


/**
 * Implements hook_theme().
 */
function colorbox_theme() {
  return array(
    'colorbox_formatter' => array(
      'variables' => array(
        'item' => NULL,
        'entity' => NULL,
        'settings' => NULL,
      ),
      'file' => 'colorbox.inc',
    ),
  );
}

/**
 * Implements hook_page_attachments().
 */
function colorbox_page_attachments(array &$page) {
  $attachment = \Drupal::service('colorbox.attachment');
  if ($attachment->isApplicable()) {
    $attachment->attach($page);
  }
}

/**
 * Implements hook_libraries_info().
 */
function colorbox_libraries_info() {
  $libraries['colorbox'] = array(
    'name' => 'Colorbox plugin',
    'vendor url' => 'http://www.jacklmoore.com/colorbox',
    'download url' => 'https://github.com/jackmoore/colorbox/archive/1.x.zip',
    'version arguments' => array(
      'file' => 'jquery.colorbox-min.js',
      'pattern' => '@(?i:Colorbox)\sv?([0-9\.a-z]+)@',
      'lines' => 5,
    ),
    'files' => array(
      'js' => array(
        'jquery.colorbox-min.js',
      ),
    ),
    'variants' => array(
      'minified' => array(
        'files' => array(
          'js' => array(
            'jquery.colorbox-min.js',
          ),
        ),
      ),
      'source' => array(
        'files' => array(
          'js' => array(
            'jquery.colorbox.js',
          ),
        ),
      ),
    ),
  );

  return $libraries;
}
