extra:
  load: '0'
  inline: '0'
custom:
  style: 'default'
  activate: '0'
  transition_type: 'elastic'
  transition_speed: '350'
  opacity: '0.85'
  text_current: '{current} of {total}'
  text_previous: '« Prev'
  text_next: 'Next »'
  text_close: 'Close'
  overlayclose: '1'
  maxwidth: '98%'
  maxheight: '98%'
  initialwidth: '300'
  initialheight: '250'
  fixed: '1'
  scrolling: '1'
  slideshow:
    slideshow: '0'
    auto: '1'
    speed: '2500'
    text_start: 'start slideshow'
    text_stop: 'stop slideshow'
advanced:
  mobile_detect: '1'
  mobile_device_width: '480px'
  caption_trim: '0'
  caption_trim_length: '75'
  visibility: '0'
  pages: 'admin*\nimagebrowser*\nimg_assist*\nimce*\nnode/add/*\nnode/*/edit\nprint/*\nprintpdf/*\nsystem/ajax\nsystem/ajax/*'
  compression_type: 'minified'
insert:
  image_style: ''
  insert_gallery: '0'
